### ISSUE TITLE
compare vectors?

### ISSUE THREAD

**Issue by morganpackard** [andik/adaptest#1]
Hi @andik. What's the best way to test equality between the elements of two vectors using adaptest? I could loop over every element and call TEST every time, but that could be ugly if there's a lot of mismatches. Do you have any built-in vector or buffer equality checking?

**Comment by andik** [comment]
Hi Morgan,

Yep, this was the Reason for writing adaptest. Use TEST(buf, bugles, buf1, buf2, name). you require the adaptest/buf.h header and plain float Arrays. see the examples in adaptest repository. You can also easily write your own test_xyz method to compare whatever you want for example TonicFrames. Just add them to the Tonic Testcase Base class in TonicTest.h.
Greetings

**Comment by morganpackard** [comment]
Awesome!

On Mon, Feb 23, 2015 at 1:46 PM, andik notifications@github.com wrote:

> Hi Morgan,
> 
> Yep, this was the Reason for writing adaptest. Use TEST(buf, bugles, buf1,
> buf2, name). you require the adaptest/buf.h header and plain float Arrays.
> see the examples in adaptest repository. You can also easily write your own
> test_xyz method to compare whatever you want for example TonicFrames. Just
> add them to the Tonic Testcase Base class in TonicTest.h.
> Greetings
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/andik/adaptest/issues/1#issuecomment-75604907.

## 

# 

Morgan Packard
cell: (720) 891-0122
twitter: @morganpackard

**Comment by andik** [comment]
don't forget to look into you build directory and open these .html files ^^
