### ISSUE TITLE
Visual studio gets a bit confused by the macros

### ISSUE THREAD

**Issue by morganpackard** [andik/adaptest#2]
Hi! I've been writing some tests, successfully, using Visual Studio. Everything works as expected, but the visual studio auto-indent machinery gets pretty confused by the macros. I think there's probably no way around this, and it's something you suspected would happen. But wanted to report that yes, IDE's don't love those complicated macros.

**Comment by andik** [comment]
Hey morgan, could you try:

``` c++
TEST(...) 
{
   // ...testing Code
}
END_TEST()
```

to see if this works better. If so I can change the macros a little....

**Comment by morganpackard** [comment]
Will do. It will be at least a week though. On vacation and away from the work PC.
